org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
neo_version_range=[21.1.248,21.2)
loader_version_range=[4,)

mod_id=structure_dfu_cache
mod_name=Structure DFU Cache
mod_license=GPL-3.0-or-later
mod_version=1.0.1
mod_group_id=dev.rinchan
mod_authors=RinChan
mod_description=Startup-time persistent cache for upgrading resolved structure templates with Minecraft's official DFU.
